### ISSUE TITLE
可以弄个简单demo吗？

### ISSUE THREAD

**Issue by sxruan** [qiuhd2015/anima#1]

**Comment by sxruan** [comment]
我测试了下抛出异常：
java.lang.NullPointerException
    at org.hdl.anima.surrogate.ServerSurrogateMgr.clientSessionCreated(ServerSurrogateMgr.java:97)
    at org.hdl.anima.fronend.FrontendServer$HandSnakeHandler.handleHandSnake(FrontendServer.java:253)
    at org.hdl.anima.fronend.FrontendServer$HandSnakeHandler.received(FrontendServer.java:220)
    at org.hdl.anima.remoting.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:69)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
2015-04-02 18:24:18 WARN  ServerHandler[Gate1]-thread-4 ChannelEventRunnable:71 - ChannelEventRunnable handle RECEIVED operation error, channel is PC201407011329/192.168.2.105:8601 -> PC201407011329/192.168.2.105:57313, message is Request{requestId=1, type=request, sessionId=2, sequence=1, twoWay=true, broken=false}
java.lang.NullPointerException: null

#     at org.hdl.anima.surrogate.ServerSurrogateMgr.getSurrogate(ServerSurrogateMgr.java:59) ~[classes/:na]

看了下源码，貌似要有多个服务器组合。。。。
正常搭建应该怎么弄呢？
我通过这种方式启动也不知道对不对？？
        Application appServer = Application.create();
        appServer.start();

**Comment by qiuhd2015** [comment]
抱歉，anima 框架正在开发中，时间问题，暂时搁置。四月下旬会完善设计文档、bug、设计上的缺陷。希望继续关注。。。
你的启动的代码是正确的，至于demo的话我最近整理下发到gitbub。。

消息流程是这样：
Client -> FrontServer -> BackendServer 
从错误可以看出你模拟发送捂手消息，并且与服务器握手成功，成功之后ServerSurrogateMgr组件发送创建BackenSession消息给后端服务器，这时报错。。

报的错误可能是前段服务器Application.xml 配置文件中未配置
<frontend-to-backends>
  <frontend-to-backend connect-server-id="game_server_1" remoteIP="172.19.60.134"      remotePort="8602" connectTimout="3000" connects="1" reconnect="true" sendReconnect="true"/>
</frontend-to-backends>

或者你没有启动后台服务器，也有可能ServerSurrogateMgr 连接不上你的后端server

**Comment by qiuhd2015** [comment]
抱歉，anima 框架正在开发中，时间问题，暂时搁置。四月下旬会完善设计文档、bug、设计上的缺陷。希望继续关注。。。
你的启动的代码是正确的，至于demo的话我最近整理下发到gitbub。。

消息流程是这样：
Client -> FrontServer -> BackendServer 
从错误可以看出你模拟发送捂手消息，并且与服务器握手成功，成功之后ServerSurrogateMgr组件发送创建BackenSession消息给后端服务器，这时报错。。

报的错误可能是前段服务器Application.xml 配置文件中未配置
<frontend-to-backends>
  <frontend-to-backend connect-server-id="game_server_1" remoteIP="172.19.60.134"      remotePort="8602" connectTimout="3000" connects="1" reconnect="true" sendReconnect="true"/>
</frontend-to-backends>

或者你没有启动后台服务器，也有可能ServerSurrogateMgr 连接不上你的后端server
